Fix CI pipeline test reporting and coverage
It turns out artifacts cannot be collected from /tmp as these temporary
files appear to be removed before gitlab CI collects them. This results
in:

> Uploading artifacts...
> WARNING: /tmp/go-tests-report.xml: no matching files
> ERROR: No files to upload

To fix this we first create an unprivileged reports/coverage directory
as part of preparing for tests.