testhelper: Improve error message on ProtoEqual
When testhelper.ProtoEqual failed it printed the following message:

    Error:      	Should be empty, but was ...

This is confusing, because the expected result was not empty, but the
diff should be empty. This change improves the error message to:

    Error:      	Protobufs not equal
    Diff: ...