Fix positional argument error when file starts with `-`
Contributes to https://gitlab.com/gitlab-org/gitlab/-/issues/393553

**Problem**

We provide file path in Args list, but it does not support files that
start with dash at the beginning.

```
git ls-tree HEAD -test
error: unknown switch `e'
```

**Solution**

Provide path in PostSepArgs list.

```
git ls-tree HEAD -- -test
```

This command supports files that start with dash.

Changelog: fixed